# Generated by Django 5.1.6 on 2025-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_and_factory', '0002_alter_contarct_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_product',
            name='condition_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market_product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='market_product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='market_product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='market_product',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('out_of_stock', 'out_of_stock')], default='available', max_length=100),
        ),
    ]
