# Generated by Django 5.1.6 on 2025-06-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_and_factory', '0003_market_product_condition_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunction_request',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_and_factory.factory'),
        ),
        migrations.AddField(
            model_name='malfunction_request',
            name='periority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=100),
        ),
        migrations.AlterField(
            model_name='malfunction_request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='malfunction_request',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
