# Generated by Django 5.1.6 on 2025-06-22 16:47

import machine_and_factory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_and_factory', '0004_malfunction_request_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contarct',
            name='file',
            field=models.FileField(upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='machine',
            name='catalog',
            field=models.FileField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='malfunction_invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='malfunction_report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='malfunction_request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='market_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
        migrations.AlterField(
            model_name='market_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=machine_and_factory.models.upload_to),
        ),
    ]
