# Generated by Django 5.1.6 on 2025-07-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_and_factory', '0005_alter_contarct_file_alter_machine_catalog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automation_request',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='contarct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='malfunction_invoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='malfunction_report',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='malfunction_request',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='malfunction_type',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='market_category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='market_order_request',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='market_product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shipping_detials',
            options={'ordering': ['-id']},
        ),
    ]
