# Generated by Django 5.1.6 on 2025-06-22 16:47

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_invoice',
            name='invoice',
            field=models.FileField(upload_to=service.models.upload_to),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=service.models.upload_to),
        ),
    ]
