# Generated by Django 5.1.6 on 2025-06-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine_and_factory', '0002_alter_contarct_signature'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=50, verbose_name='Status')),
                ('target_audience', models.TextField(verbose_name='Target Audience')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campaigns/', verbose_name='Attachment')),
                ('on_click', models.CharField(choices=[('market_page', 'Market Page'), ('service_page', 'Service Page'), ('factory_page', 'Factory Page'), ('machine_page', 'Machine Page'), ('other_page', 'Other Page'), ('external_link', 'External Link')], default='open_url', max_length=50, verbose_name='On Click Action')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Page')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_and_factory.factory', verbose_name='Factory')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_and_factory.machine', verbose_name='Machine')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_and_factory.market_product', verbose_name='Market')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
