# Generated by Django 5.1.6 on 2025-06-22 16:37

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=campaigns.models.upload_to, verbose_name='Attachment'),
        ),
    ]
