# Generated by Django 5.1.6 on 2025-07-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id']},
        ),
    ]
