# Generated by Django 5.1.6 on 2025-06-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_and_factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contarct',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
